name: Upload To Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: 'Select the environment'
        required: true
        default: 'staging'
        options: [ 'staging', 'release' ]
      version_bump:
        type: choice
        description: 'Type of version bump'
        required: true
        default: 'patch'
        options: [ 'major', 'minor', 'patch' ]
      custom_notes:
        type: textarea
        description: 'Custom release notes (optional)'
        required: false
      notify_testers:
        type: boolean
        description: 'Notify testers about this build'
        required: false
        default: true
      debug_build:
        type: boolean
        description: 'Build debug APK (uncheck for release APK)'
        required: false
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew


      # Create APK Debug
      - name: Build APK
        run: |
          if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
            ./gradlew assembleDebug
          elif [[ "${{ github.event.inputs.environment }}" == "release" ]]; then
            ./gradlew assembleRelease
          else
            echo "Invalid environment selected"
            exit 1
          fi      

      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: |
            if [[ "${{ github.event.inputs.environment }}" == "staging" ]]; then
              app/build/outputs/apk/debug/app-debug.apk
            elif [[ "${{ github.event.inputs.environment }}" == "release" ]]; then
              app/build/outputs/apk/release/app-release.apk
            else
              echo "Invalid environment selected"
              exit 1
            fi      
